#!/usr/bin/env python3
"""文案表：默认英文，?lang=zh 切中文。

站点面向的是海外站主（Shopify / WooCommerce / 自建站），报告与页面默认英文；
中文版保留给国内独立站卖家这个受众。

两份文案必须同结构：加 key 时两个语言都要加，否则会静默回落到英文。
"""
import re

LANGS = ("en", "zh")
DEFAULT = "en"

STR = {
    # ---------------------------------------------------------------- 首页
    "en": {
        "site.title": "AgentBI — Is your site ready for AI agents?",
        "site.sub": "Enter a URL. See whether an AI agent can find, understand and buy from your site.",
        "site.placeholder": "https://your-store.com",
        "site.button": "Scan",
        "site.scanning": "Scanning, 10–20 seconds…",
        "site.lb_link": "Leaderboard: 225 stores tested →",
        "site.checks": "Checks: can agents fetch you · product structured data · UCP deployment "
                       "and version · llms.txt · robots. Open source and reproducible:",
        "site.about_link": "How we crawl / how to opt out",
        "site.issues_link": "Wrong result? Open an issue",
        "site.cached": "(from cache)",
        "site.req_failed": "Request failed: {err}",
        "site.err": "✗ {msg}",

        # 订阅。文案刻意不承诺发送节奏——发送通道还没接，承诺了就是骗人。
        "sub.title": "Weekly digest",
        "sub.desc_long": "I re-scan the same 225 stores every day. Leave your email and you'll get "
                         "the weekly digest when it starts: UCP version moves, new deployments, "
                         "and what changed week over week.",
        "sub.placeholder": "you@your-store.com",
        "sub.button": "Notify me",
        "sub.consent": "Used only to send the digest. No tracking, no sharing, unsubscribe any time.",
        "sub.ok": "Got it — you're on the list.",
        "sub.err_invalid": "That doesn't look like an email address.",
        "sub.err_rate": "Too many attempts. Try again in a while.",
        "sub.err_fail": "Something broke on my side. Try again, or open an issue.",

        "dim.fetch": "Fetchable by agents",
        "dim.structured": "Product structured data",
        "dim.ucp": "UCP manifest",
        "dim.llms": "llms.txt",
        "dim.robots": "robots.txt",

        "rep.checked": "Checked",
        "rep.probe": "Multi-UA probe",
        "rep.ua": "UA",
        "rep.status": "status",
        "rep.product": "product data",
        "rep.result": "result",
        "rep.readable": "readable",
        "rep.blocked": "✗ blocked",
        "rep.ok": "✓",
        "rep.ucp_title": "UCP manifest",
        "rep.ucp_current": "Current version {v}, compatible with {versions}",
        "rep.service": "service",
        "rep.version": "version",
        "rep.transport": "transport",
        "rep.fixes": "What to fix",
        "rep.warn": "⚠ {note}",

        "err.bad_url": "Invalid URL (http/https only)",
        "err.rate": "Too many requests, try again shortly",
        "err.cooldown": "That site was just scanned, try again in {n} minutes",
        "err.busy": "Busy right now, retry in 30 seconds",

        "lb.title": "AgentBI leaderboard",
        "lb.back": "← Scan your site",
        "lb.by_platform": "By platform",
        "lb.th_platform": "Platform",
        "lb.th_n": "Stores",
        "lb.th_ucp": "UCP",
        "lb.th_product": "Product JSON-LD",
        "lb.th_llms": "llms.txt",
        "lb.th_avg": "Avg score",
        "lb.method": "Method and limitations (read before quoting)",
        "lb.m1": "Snapshot <b>{date}</b>: {scanned} stores scanned, "
                 "<b>{reach}</b> returned 200 and are evaluable, {unreach} returned non-200 "
                 "({n403} of them 403).",
        "lb.m2": "<b>A 403 is our IP reputation, not their configuration</b> — most are "
                 "enterprise WAFs blocking datacenter egress (Walmart, Macy's, Nordstrom, "
                 "Costco are all in there). Full browser headers were tried and did not "
                 "reproduce. This table covers stores <b>without</b> an enterprise WAF, "
                 "not the industry.",
        "lb.m3": "<b>WooCommerce n={n}</b>, every site harvestable from WooCommerce's own "
                 "showcase. A direction, not a precise ratio.",
        "lb.m4": "On Shopify, <code>llms.txt</code> and UCP are mostly "
                 "<b>generated by the platform</b> (several stores ship byte-identical "
                 "templates) — it's a platform dividing line, not a signal of effort.",
        "lb.m5": "Scoring is <b>heuristic</b>: no JS rendering, and it does not place a real "
                 "order through UCP — it only checks that the manifest exists and its version.",
        "lb.m6": "Compared with the previous snapshot ({pdate}): evaluable {reach_delta}, "
                 "UCP deployed {ucp_delta}. <b>The evaluable count fluctuates day to day</b> "
                 "— the same list can differ by a dozen depending on each site's WAF and our "
                 "egress reputation, so quote these numbers with their snapshot date.",
        "lb.detail": "Detail (evaluable {reach} / scanned {scanned})",
        "lb.th_site": "Site",
        "lb.note_unreach": "{n} sites returned non-200 to the scanner (mostly WAF blocks). "
                          "That is not a judgement on their agent-readiness; they are not "
                          "counted here.",
        "lb.no_data": "No leaderboard data yet",
        "lb.dash": "—",

        "about.title": "About AgentBI",
        "about.h_what": "What this is",
        "about.p_what": "AgentBI measures how friendly a site is to AI agents: can an agent "
                        "fetch your pages, is your product data machine-readable (JSON-LD "
                        "price / availability), have you deployed a UCP manifest, do you "
                        "publish <code>llms.txt</code>.",
        "about.h_how": "How we crawl",
        "about.li1": "<b>Only when someone submits a URL.</b> No continuous crawling.",
        "about.li2": "User agent is honest and identifiable: "
                     "<code>agentbi/0.1 (+https://agentbi.tech/about; agent-readiness scanner)</code>"
                     " — not disguised as a browser.",
        "about.li3": "One check is about 10 requests to your site and takes 15–20 seconds.",
        "about.li4": "<b>One real scan per domain per 10 minutes</b>; results cached 30 minutes.",
        "about.li5": "Results are published on the <a href=\"/leaderboard\">leaderboard</a>.",
        "about.h_exception": "One exception, explained",
        "about.p_exception": "One step, the multi-UA probe, requests your site with several real "
                        "AI agent identifiers (GPTBot, ClaudeBot, …) and <b>one real browser "
                        "identifier</b>, then compares the responses — to answer \"do you treat "
                        "agents differently from normal visitors\". <b>This only measures "
                        "anything if the identifiers are real</b>, so it is a measurement, not "
                        "anonymous crawling. Every other fetch uses the honest agent above.",
        "about.h_optout": "Don't want to be scanned",
        "about.p_optout": "robots.txt is not honoured automatically yet — known TODO. Two ways out:",
        "about.li_issue": "<b>(preferred) Open an issue</b> with the "
                          "<a href=\"https://github.com/JamesChief/agentbi/issues/new?template=opt-out.yml\">"
                          "\"stop scanning\" template</a> and we add the domain to the blocklist, "
                          "which is checked before fetching.",
        "about.li_email": "Email: <a href=\"mailto:contact@agentbi.tech\">"
                          "<code>contact@agentbi.tech</code></a> — reply \"stop\" and the domain "
                          "is added to the blocklist",
        "about.h_data": "Data",
        "about.p_data": "Results are published on the leaderboard. Only sites returning 200 are "
                        "counted; sites returning non-200 (mostly enterprise WAFs) are absent "
                        "and are not read as \"low agent-readiness\".",
        "about.back": "← Back to scanning",

        "og.site_name": "AgentBI",
        "og.home_title": "AgentBI — Is your site ready for AI agents?",
        "og.home_desc": "86% of Shopify stores already support agentic commerce. WooCommerce: 0%. "
                        "What about yours? Enter a URL, get a report in 15 seconds.",
        "og.lb_title": "AgentBI leaderboard — 225 stores tested for AI-agent readiness",
        "og.lb_desc": "Shopify 86% have UCP deployed, WooCommerce 0%. Your platform decides "
                      "whether shopping agents can find you more than your own effort does.",

        # ---------------------------------------------------------- 报告文案
        "rep.err_unreachable": "Unreachable: {err}",
        "rep.fetch_skipped": "not tested (--no-probe)",
        "rep.fetch_inconclusive": "inconclusive (scanner network restricted, not scored)",
        "rep.fetch_detail": "{ok}/{total} agents can fetch the page, "
                            "{readable} can read product/price data",
        "rep.struct_full": "Product JSON-LD complete",
        "rep.struct_partial": "partial product data",
        "rep.struct_none": "no structured product data found",
        "rep.ucp_deployed": "deployed {v}; services: {ns}, endpoints: {ne}, "
                            "compatible with {nv} earlier versions",
        "rep.ucp_html": "not deployed ({path} returns an HTML page, not a manifest)",
        "rep.ucp_status": "not deployed ({path} returns {status})",
        "rep.llms_full": "present with links",
        "rep.llms_yes": "present",
        "rep.llms_no": "absent",
        "rep.robots_blocking": "blocks {n} agent types",
        "rep.robots_none": "no robots.txt (allow by default)",
        "rep.probe_skipped_note": "multi-UA probe skipped (--no-probe)",
        "rep.header": "Checked {url}",
        "rep.checked_url": "Target  {url}  ({kind})",
        "rep.score": "Score  {score}/100",
        "rep.untested": "   [not tested: {items}]",
        "rep.probe_head": "  multi-UA probe:",
        "rep.readable_short": "readable",
        "rep.blocked_short": "✗ blocked",
        "rep.ucp_head": "  UCP manifest:",
        "rep.ucp_hist": "    version {v}  earlier versions {versions}",
        "rep.service_line": "    service {name}",
        "rep.entry_line": "      {v}  {transport}  {endpoint}",
        "rep.protocols": "  ACP/AP2 probe (unverified): {protos}",
        "rep.fixes_head": "  what to fix:",
        "rep.fix_line": "    [{pri}] {title}\n         {desc}",

        # ---------------------------------------------------------- 修复清单
        "fix.ucp_missing.title": "Deploy a UCP manifest",
        "fix.ucp_missing.desc": "{path} returns {status}. UCP has a first-hand verified "
                                "site-side marker; some Shopify stores already ship it "
                                "(observed version 2026-08-25). Without it, shopping agents "
                                "cannot discover your products or checkout entry point through "
                                "the standard flow.",
        "fix.ucp_single.title": "UCP declares only one version",
        "fix.ucp_single.desc": "Currently {v}. Declaring earlier versions keeps agents that "
                               "have not upgraded working.",
        "fix.llms.title": "Add /llms.txt",
        "fix.llms.desc": "Give agents a plain-text sitemap: key pages plus a one-line "
                         "description. Put it at the site root.",
        "fix.jsonld.title": "Add Product JSON-LD",
        "fix.jsonld.desc": "Embed <script type=\"application/ld+json\"> on product pages with "
                           "@type=Product including name/brand/sku/image/description.",
        "fix.price.title": "Complete the Offer price",
        "fix.price.desc": "In Product.offers provide price, priceCurrency and availability — "
                          "these three are what shopping agents mainly use to decide "
                          "whether something is buyable.",
        "fix.field.title": "Add {field}",
        "fix.field.desc": "Missing structured-data field; agents get an incomplete record.",
        "fix.blocked.title": "Unblock these agents: {agents}",
        "fix.blocked.desc": "robots.txt or your WAF blocks them while the browser UA passes — "
                            "that is blocking agents specifically, and it costs you the agent "
                            "traffic and orders directly.",
        "fix.wildcard.title": "Review robots.txt User-agent: * Disallow: /",
        "fix.wildcard.desc": "The wildcard rule blocks every agent along with everything else.",
        "fix.protos.title": "ACP/AP2 probe hit: {protos}",
        "fix.protos.desc": "(site-side markers not verified first-hand; evidence only, "
                           "not a conclusion)",
        "pri.high": "high",
        "pri.medium": "medium",
        "pri.low": "low",
    },

    # ---------------------------------------------------------------- 中文
    "zh": {
        "site.title": "AgentBI — 你的网站对 AI agent 有多友好",
        "site.sub": "输入网址，看你的网站能被 AI agent 找到、读懂、下单吗。",
        "site.placeholder": "https://your-store.com",
        "site.button": "检测",
        "site.scanning": "检测中，约需 10–20 秒…",
        "site.lb_link": "查看榜单（225 家电商站实测）→",
        "site.checks": "检测项：agent 能否抓取 · 产品结构化数据 · UCP 部署与版本 · llms.txt · "
                       "robots。工具开源，数据可复现：",
        "site.about_link": "我们怎么抓站 / 如何让我们不抓你",
        "site.issues_link": "结果有误？来提 issue",
        "site.cached": "（来自缓存）",
        "site.req_failed": "请求失败：{err}",
        "site.err": "✗ {msg}",

        # 订阅。文案刻意不承诺发送节奏——发送通道还没接，承诺了就是骗人。
        "sub.title": "每周摘要",
        "sub.desc_long": "我每天重扫这 225 家站。留下邮箱，每周摘要开始发的时候你会收到第一期："
                         "UCP 版本变化、新部署的站点、以及和上一周的环比。",
        "sub.placeholder": "you@your-store.com",
        "sub.button": "订阅",
        "sub.consent": "只用于发送摘要，不做追踪、不对外共享，随时可退订。",
        "sub.ok": "收到了，已经记下。",
        "sub.err_invalid": "这个邮箱地址看起来不对。",
        "sub.err_rate": "操作太频繁，稍后再试。",
        "sub.err_fail": "我这边出错了。稍后再试，或开个 issue 告诉我。",

        "dim.fetch": "agent 能否抓取",
        "dim.structured": "产品结构化数据",
        "dim.ucp": "UCP manifest",
        "dim.llms": "llms.txt",
        "dim.robots": "robots.txt",

        "rep.checked": "检测对象",
        "rep.probe": "多 UA 探测",
        "rep.ua": "UA",
        "rep.status": "状态",
        "rep.product": "产品数据",
        "rep.result": "结果",
        "rep.readable": "可读",
        "rep.blocked": "✗ 被拦",
        "rep.ok": "✓",
        "rep.ucp_title": "UCP manifest",
        "rep.ucp_current": "当前版本 {v}，兼容历史版本 {versions}",
        "rep.service": "服务",
        "rep.version": "版本",
        "rep.transport": "传输",
        "rep.fixes": "修复清单",
        "rep.warn": "⚠ {note}",

        "err.bad_url": "URL 不合法（仅支持 http/https）",
        "err.rate": "请求过于频繁，请稍后再试",
        "err.cooldown": "该站点刚被检测过，请 {n} 分钟后再试",
        "err.busy": "现在排队检测的人较多，请 30 秒后重试",

        "lb.title": "AgentBI 榜单",
        "lb.back": "← 检测你的站",
        "lb.by_platform": "按平台对比",
        "lb.th_platform": "平台",
        "lb.th_n": "站数",
        "lb.th_ucp": "UCP",
        "lb.th_product": "产品结构化数据",
        "lb.th_llms": "llms.txt",
        "lb.th_avg": "平均分",
        "lb.method": "方法与局限（引用前请先读）",
        "lb.m1": "数据快照 <b>{date}</b>：共扫描 {scanned} 家电商站，首页返回 200 的 "
                 "<b>{reach}</b> 家（可评估），{unreach} 家返回非 200（其中 {n403} 个是 403）。",
        "lb.m2": "<b>403 是我们的 IP 信誉问题，不是对方站点的配置问题</b>——绝大多数是企业级 WAF "
                 "拦截数据中心出口 IP（Walmart / Macy's / Nordstrom / Costco 等都在其中）。"
                 "加完整浏览器头部实测无法重现。因此本表覆盖的是<b>没有企业 WAF 的站点</b>，不是全行业。",
        "lb.m3": "<b>WooCommerce n={n}</b>，全部来自 WooCommerce 官方 showcase（可抓取的就这么些）。"
                 "这是方向性结论，不是精确比例。",
        "lb.m4": "Shopify 店铺的 <code>llms.txt</code> 与 UCP 多为<b>平台自动生成</b>"
                 "（多个店铺模板逐字节相同）——它是平台分界线，不是站主努力程度的信号。",
        "lb.m5": "评分是<b>启发式</b>的：不做 JS 渲染，也不会真的通过 UCP 下单，"
                 "只验证 manifest 是否存在及其版本。",
        "lb.m6": "较上一次快照（{pdate}）：可评估 {reach_delta}，部署 UCP {ucp_delta}。"
                 "<b>可评估数会随时间波动</b>——同一批站点在不同日期相差十几个是常态"
                 "（对方 WAF 策略与我们的出口 IP 信誉都在变），所以引用本站数字时请带上快照日期。",
        "lb.detail": "明细（可评估 {reach} / 扫描 {scanned}）",
        "lb.th_site": "站点",
        "lb.note_unreach": "{n} 个站点对探测器返回非 200（多为 WAF 拦截），"
                          "不代表其 agent 友好度低，未计入榜单。",
        "lb.no_data": "还没有榜单数据",
        "lb.dash": "—",

        "about.title": "关于 AgentBI",
        "about.h_what": "这是什么",
        "about.p_what": "AgentBI 检测一个网站对 AI agent 的友好程度：agent 能不能抓到页面、商品数据"
                        "能不能被机器读懂（JSON-LD 的价格/库存）、有没有部署 UCP manifest、"
                        "有没有 <code>llms.txt</code>。",
        "about.h_how": "我们怎么抓",
        "about.li1": "<b>只在有人提交网址时才抓</b>，不是全网持续爬取。",
        "about.li2": "用户代理标识为 "
                     "<code>agentbi/0.1 (+https://agentbi.tech/about; agent-readiness scanner)</code>，"
                     "不伪装成浏览器。",
        "about.li3": "单次检测对同一站点发起约 10 个请求，耗时 15–20 秒。",
        "about.li4": "<b>同一域名 10 分钟内只真扫一次</b>，结果缓存 30 分钟。",
        "about.li5": "结果公开在<a href=\"/leaderboard\">榜单</a>里。",
        "about.h_exception": "有一处例外，说明一下",
        "about.p_exception": "检测里有一步是「多 UA 探测」：用几个真实 AI agent 的标识"
                        "（GPTBot、ClaudeBot 等）和<b>一个真实浏览器的标识</b>各请求一次你的站点，"
                        "对比返回是否不同——这是为了回答「你的站有没有把 AI agent 和正常访客"
                        "区别对待」。<b>这一步必须是真实标识才测得出来</b>，"
                        "所以这里是测量工具，不是匿名抓取。除这一步外，"
                        "所有内容抓取都用上面那个诚实的用户代理。",
        "about.h_optout": "不想被扫",
        "about.p_optout": "目前尚未实现 robots.txt 自动遵从——这是已知的待办。可用的退出通道有两个：",
        "about.li_issue": "<b>（推荐）开一个 issue</b>："
                          "<a href=\"https://github.com/JamesChief/agentbi/issues/new?template=opt-out.yml\">"
                          "「要求停止扫描」模板</a>，把域名加进屏蔽清单，抓取前会检查。",
        "about.li_email": "邮件：<a href=\"mailto:contact@agentbi.tech\">"
                          "<code>contact@agentbi.tech</code></a>，回复 stop 即加入屏蔽清单",
        "about.h_data": "数据",
        "about.p_data": "检测结果会被公开收录进榜单。榜单只统计返回 200 的站点；对探测器返回非 200 的"
                        "站点（多为企业级 WAF 拦截）不会出现在榜单里，也不会被解读为「该站 "
                        "agent 友好度低」。",
        "about.back": "← 返回检测",

        "og.site_name": "AgentBI",
        "og.home_title": "AgentBI — 你的网站对 AI agent 有多友好",
        "og.home_desc": "Shopify 店铺 86% 已支持 agent 商务，WooCommerce 0%。你的站呢？"
                        "输入网址，15 秒出报告。",
        "og.lb_title": "AgentBI 榜单 — 225 家电商站 agent 友好度实测",
        "og.lb_desc": "Shopify 86% 已部署 UCP，WooCommerce 0%。"
                      "平台差异比站主努力更能决定你能不能被 shopping agent 找到。",

        "rep.err_unreachable": "无法访问：{err}",
        "rep.fetch_skipped": "未测（--no-probe）",
        "rep.fetch_inconclusive": "不可判定（探测器网络受限，不计分）",
        "rep.fetch_detail": "{ok}/{total} 个 agent 可取到页面，{readable} 个能读到产品/价格数据",
        "rep.struct_full": "Product JSON-LD 完整",
        "rep.struct_partial": "有部分产品数据",
        "rep.struct_none": "未找到结构化产品数据",
        "rep.ucp_deployed": "已部署 {v}，{ns} 个服务、{ne} 个 endpoint，兼容 {nv} 个历史版本",
        "rep.ucp_html": "未部署（{path} 返回 HTML 页面，非 manifest）",
        "rep.ucp_status": "未部署（{path} 返回 {status}）",
        "rep.llms_full": "有且含链接",
        "rep.llms_yes": "有",
        "rep.llms_no": "无",
        "rep.robots_blocking": "拦 {n} 类 agent",
        "rep.robots_none": "无 robots.txt（默认放行）",
        "rep.probe_skipped_note": "已跳过多 UA 探测（--no-probe）",
        "rep.header": "检测 {url}",
        "rep.checked_url": "检测对象  {url}  ({kind})",
        "rep.score": "得分  {score}/100",
        "rep.untested": "   [未测: {items}]",
        "rep.probe_head": "  多 UA 探测:",
        "rep.readable_short": "可读",
        "rep.blocked_short": "✗ 被拦",
        "rep.ucp_head": "  UCP manifest:",
        "rep.ucp_hist": "    version {v}  历史版本 {versions}",
        "rep.service_line": "    service {name}",
        "rep.entry_line": "      {v}  {transport}  {endpoint}",
        "rep.protocols": "  ACP/AP2 探针（未核实）: {protos}",
        "rep.fixes_head": "  修复清单:",
        "rep.fix_line": "    [{pri}] {title}\n         {desc}",

        "fix.ucp_missing.title": "部署 UCP manifest",
        "fix.ucp_missing.desc": "{path} 返回 {status}。UCP 已有一手核实的站点侧标识，"
                                "Shopify 部分店铺已自动部署（实测版本 2026-08-25）。"
                                "缺它意味着 shopping agent 无法按标准流程发现你的商品与下单入口。",
        "fix.ucp_single.title": "UCP 只声明单一版本",
        "fix.ucp_single.desc": "当前 {v}。多声明历史版本可兼容尚未升级的 agent。",
        "fix.llms.title": "加 /llms.txt",
        "fix.llms.desc": "给 agent 一份纯文本站点地图：核心页面 + 一句话说明。放站点根目录。",
        "fix.jsonld.title": "加 Product JSON-LD",
        "fix.jsonld.desc": "商品页嵌 <script type=\"application/ld+json\">，@type=Product，"
                           "含 name/brand/sku/image/description。",
        "fix.price.title": "补齐 Offer 价格",
        "fix.price.desc": "Product.offers 里给 price、priceCurrency、availability——"
                          "shopping agent 主要靠这三个字段判断是否可买。",
        "fix.field.title": "补 {field}",
        "fix.field.desc": "结构化数据字段缺失，agent 读到的信息不完整。",
        "fix.blocked.title": "放行被拦的 agent: {agents}",
        "fix.blocked.desc": "robots.txt 或 WAF 把这些 agent 挡了，且浏览器 UA 没被挡——"
                            "属于只挡 agent，会直接损失 agent 带来的流量与订单。",
        "fix.wildcard.title": "检查 robots.txt 的 User-agent: * Disallow: /",
        "fix.wildcard.desc": "通配规则会一并挡住所有 agent。",
        "fix.protos.title": "ACP/AP2 探针命中: {protos}",
        "fix.protos.desc": "（站点侧标识尚未一手核实，仅作证据，不作为结论）",
        "pri.high": "高",
        "pri.medium": "中",
        "pri.low": "低",
    },
}


def t(key, lang=DEFAULT, **kw):
    """取值；缺 key 静默回落到英文（加文案时两个语言都要加）。"""
    s = STR.get(lang, {}).get(key) or STR[DEFAULT].get(key, key)
    return s.format(**kw) if kw else s


_PH = re.compile(r"\{\{(\w[\w.]*)\}\}")


def render_template(text, lang):
    """把模板里的 {{key}} 换成当前语言的文案。"""
    return _PH.sub(lambda m: t(m.group(1), lang), text)
